### ISSUE TITLE
ModuleNotFoundError: No module named 'waitingspinnerwidget'

### ISSUE THREAD

**Issue by flameboii** [hdbhdb/qtube#2]
I've installed the remaining modules manually after the command to run qtube threw similar errors but pip can't seem to find this one.

`ERROR: Could not find a version that satisfies the requirement waitingspinnerwidget

ERROR: No matching distribution found for waitingspinnerwidget`

Thanks.

**Comment by ghost** [comment]
For some reason, the developer didn't write that another module had to be installed, and this is https://github.com/z3ntu/QtWaitingSpinner. You need to clone that repository and do `python setup.py install`.

It still doesn't work for me, but it's only on Windows, I hope it will work perfectly on Linux.

**Comment by hdb** [comment]
thanks! fixed with 49329ec78cdbcc08eda719b708c2404a958c5a88
